version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/usr/src/app
    networks:
      - my-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
